import { themes as prismThemes } from 'prism-react-renderer';
import type { Config } from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

const config: Config = {
  // ------------------------------------------------------------
  // 1. SITE METADATA - Kixago Updates
  // ------------------------------------------------------------
  title: 'Kixago DeFi Aggregator API',
  tagline: 'The unified API for multi-chain DeFi protocol data.',
  favicon: 'img/favicon.ico',

  // Future flags, see https://docusaurus.iokixago-docs/api/docusaurus-config#future
  future: {
    v4: true,
  },

  // Set the production url of your site here
  url: 'https://docs.kixago.com', // Update with your eventual documentation domain
  // Set the /<baseUrl>/ pathname under which your site is served
  baseUrl: '/',

  // GitHub pages deployment config.
  organizationName: 'kixago', // Replace with your GitHub organization name
  projectName: 'defi-aggregator-api', // Replace with your repository name

  onBrokenLinks: 'throw',

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  // ------------------------------------------------------------
  // 2. PLUGINS ARRAY - ADD OPENAPI INTEGRATION
  // ------------------------------------------------------------
  plugins: [
    [
      'docusaurus-plugin-openapi-docs',
      {
        id: "api-reference",
        docsPath: "docs/api", 
        config: {
          positions: { 
            // NOTE: Path is relative to docs-site, so we look up one directory for openapi.yaml
            specPath: "../openapi.yaml", 
            outputDir: "docs/api/positions", 
            sidebarOptions: {
              groupPathsBy: "tag", 
            },
          },
        },
      },
    ],
  ],


  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          // Remove or update the editUrl to point to your actual repo path
          editUrl:
            'https://github.com/kixago/defi-aggregator-api/tree/main/docs-site/', 
        },
        blog: {
          showReadingTime: true,
          feedOptions: {
            type: ['rss', 'atom'],
            xslt: true,
          },
          editUrl:
            'https://github.com/kixago/defi-aggregator-api/tree/main/docs-site/',
          onInlineTags: 'warn',
          onInlineAuthors: 'warn',
          onUntruncatedBlogPosts: 'warn',
        },
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    // Replace with your project's social card
    image: 'img/kixago-social-card.jpg',
    colorMode: {
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: 'Kixago API',
      logo: {
        alt: 'Kixago Logo',
        src: 'img/logo.svg',
      },
      items: [
        // 3. UPDATE NAVBAR LINK
        {
          type: 'docSidebar',
          sidebarId: 'guideSidebar', // This ID is what you'll use for your main documentation (Quickstart/Guides)
          position: 'left',
          label: 'Guides',
        },
        {
          type: 'docSidebar',
          sidebarId: 'apiSidebar', // Assuming you name your autogenerated sidebar 'docsSidebar' in sidebars.ts
          position: 'left',
          label: 'API Reference',
        },
        {to: '/blog', label: 'Blog', position: 'left'},
        {
          href: 'https://github.com/kixago/defi-aggregator-api',
          label: 'GitHub',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Docs',
          items: [
            {
              label: 'Quickstart',
              to: 'kixago-docs/intro',
            },
            {
              label: 'API Reference',
              to: 'kixago-docs/api/overview', // Link to your generated API overview page
            },
          ],
        },
        {
          title: 'More',
          items: [
            {
              label: 'GitHub',
              href: 'https://github.com/kixago/defi-aggregator-api',
            },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} Kixago, Inc. Built with Docusaurus.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      // Add Go for code highlighting
      additionalLanguages: ['go'], 
    } satisfies Preset.ThemeConfig,
  },
};

export default config;
