// docs-site/sidebars.ts

const sidebars = {
  // Use 'guideSidebar' for all your manual documentation pages
  guideSidebar: [
    'intro', // Example: your introduction page
    {
      type: 'category',
      label: 'Quickstart',
      items: [
        'quickstart/setup',
        'quickstart/auth',
      ],
    },
    // Add other conceptual documents here
  ],
  
  // Use 'apiSidebar' for the auto-generated API Reference
  apiSidebar: [
    {
      type: 'category',
      label: 'API Reference',
      link: {
        type: 'generated-index',
        title: 'Kixago API Reference',
        description: 'The complete specification for the Kixago DeFi Aggregator API.',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/positions', // This path is configured in docusaurus.config.ts
        },
      ],
    },
  ],
};

export default sidebars;
