// docs-site/sidebars.ts

import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Main documentation sidebar
  guideSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Quick Start',
      collapsed: false,
      items: [
        'quickstart/setup',
        'quickstart/auth',
      ],
    },
    {
      type: 'category',
      label: 'Code Examples',
      collapsed: false,
      items: [
        'examples/index',
      ],
    },
  ],
  
  // API Reference sidebar (auto-generated from OpenAPI)
  apiSidebar: [
    {
      type: 'category',
      label: 'API Reference',
      link: {
        type: 'generated-index',
        title: 'Kixago API Reference',
        description: 'Complete API documentation with examples and schemas.',
        slug: '/api',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/positions',
        },
      ],
    },
  ],
};

export default sidebars;
